In [2]:
import numpy as np
from PIL import Image

# Make a simple 2x2 RGB image
data = np.array([
    [[255, 0, 0], [0, 255, 0]],   # Red, Green
    [[0, 0, 255], [255, 255, 0]]  # Blue, Yellow
], dtype=np.uint8)


img = Image.fromarray(data, 'RGB')
img.show()

print("Raw array shape:", data.shape)
print("Raw values:\n", data)


Raw array shape: (2, 2, 3)
Raw values:
 [[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255   0]]]


C:\Users\Adnan Habib\AppData\Local\Temp\ipykernel_12796\2458747707.py:11: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(data, 'RGB')


In [8]:
import numpy as np
from PIL import Image

# Create a 3x3 RGB image
data = np.array([
    [[255, 0, 0],   [0, 255, 0],   [0, 0, 255]],    # Red, Green, Blue
    [[255, 255, 0], [0, 255, 255], [255, 0, 255]],  # Yellow, Cyan, Magenta
    [[128, 128, 128], [255, 255, 255], [0, 0, 0]]   # Gray, White, Black
], dtype=np.uint8)

img = Image.fromarray(data, 'RGB')
img.show()

print("Raw array shape:", data.shape)
print("Raw values:\n", data)


Raw array shape: (3, 3, 3)
Raw values:
 [[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [  0 255 255]
  [255   0 255]]

 [[128 128 128]
  [255 255 255]
  [  0   0   0]]]


C:\Users\Adnan Habib\AppData\Local\Temp\ipykernel_12796\1976312741.py:11: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(data, 'RGB')


In [9]:
import torch
import torchvision.transforms as T

# Convert to tensor (PyTorch uses CHW: Channels, Height, Width)
to_tensor = T.ToTensor()
tensor_img = to_tensor(img)

print("Tensor shape:", tensor_img.shape)


Tensor shape: torch.Size([3, 3, 3])


In [30]:
img=Image.open('emoji.png')
# img.show()
img= img.resize((32,32))

print(img.size)
img_array = np.array(img)
print("Image size (width, height):", img.size)
print("Shape of array (H, W, C):", img_array.shape)


(32, 32)
Image size (width, height): (32, 32)
Shape of array (H, W, C): (32, 32, 3)


In [32]:
# print("RGB matrix:\n", img_array[30])
# for i in range(30, 40):
#     print(img_array[i])

In [61]:
transform = T.ToTensor()
img_tensor = transform(img)

In [62]:
img_tensor= img_tensor.unsqueeze(0)  # Add batch dimension
print("Tensor shape (B, C, H, W):", img_tensor.shape)
print("Tensor values:\n", img_tensor)

Tensor shape (B, C, H, W): torch.Size([1, 3, 32, 32])
Tensor values:
 tensor([[[[0.3882, 0.3882, 0.3882,  ..., 0.3882, 0.3882, 0.3882],
          [0.3882, 0.3882, 0.3882,  ..., 0.3882, 0.3882, 0.3882],
          [0.3882, 0.3882, 0.3882,  ..., 0.3882, 0.3882, 0.3882],
          ...,
          [0.3882, 0.3882, 0.3804,  ..., 0.3882, 0.3882, 0.3882],
          [0.3882, 0.3882, 0.3882,  ..., 0.3882, 0.3882, 0.3882],
          [0.3882, 0.3882, 0.3882,  ..., 0.3882, 0.3882, 0.3882]],

         [[0.5882, 0.5882, 0.5882,  ..., 0.5882, 0.5882, 0.5882],
          [0.5882, 0.5882, 0.5882,  ..., 0.5882, 0.5882, 0.5882],
          [0.5882, 0.5882, 0.5882,  ..., 0.5882, 0.5882, 0.5882],
          ...,
          [0.5882, 0.5882, 0.5922,  ..., 0.5882, 0.5882, 0.5882],
          [0.5882, 0.5882, 0.5882,  ..., 0.5882, 0.5882, 0.5882],
          [0.5882, 0.5882, 0.5882,  ..., 0.5882, 0.5882, 0.5882]],

         [[0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
          [0.9255, 0.9255, 0.9255,  ..

In [63]:
img_tensor.shape

torch.Size([1, 3, 32, 32])

In [64]:
import torch.nn as nn

In [65]:
conv1 = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, stride=1, padding=1)


In [66]:
output = conv1(img_tensor)
print("Output shape after Conv2d:", output.shape)


Output shape after Conv2d: torch.Size([1, 64, 32, 32])


In [71]:
len(output[0][0][0])

32

In [167]:
x = torch.randn(1, 4,8)
print(x)

tensor([[[ 0.1912, -1.0700,  1.2381,  1.0358, -0.3722, -0.3079,  0.0822,
           0.9230],
         [-1.4085,  0.2772,  0.3883, -1.3357, -0.7279,  0.3466, -0.2030,
          -0.1040],
         [-0.3655, -1.6868,  0.2347,  2.1797,  0.0920,  1.3699, -1.6303,
          -1.6722],
         [-0.4250,  0.4998, -1.4255, -0.6987,  1.9643,  0.5322,  0.6776,
          -0.1829]]])


In [170]:

print(x.shape)
qkv = nn.Linear(8, 24)(x) 
print(qkv.shape)


torch.Size([1, 4, 8])
torch.Size([1, 4, 24])


In [169]:
Q=qkv[:, :, :8]
K=qkv[:, :, 8:16]
V=qkv[:, :, 16:]
print(Q)
print(qkv[0][0])

tensor([[[-0.5684,  0.2852,  0.1358, -0.0923,  0.2989,  0.0778, -1.1424,
           0.5875],
         [ 0.9549, -0.1833,  1.1566, -0.3844,  0.0771,  0.1366,  0.3882,
          -1.2462],
         [ 0.5960, -0.8793,  0.9915, -0.0793,  0.7765,  0.3699, -1.0047,
          -0.6748],
         [ 0.4899,  0.3007, -0.1053, -0.2095,  0.7283,  0.3676,  0.0085,
          -0.8186]]], grad_fn=<SliceBackward0>)
tensor([-0.5684,  0.2852,  0.1358, -0.0923,  0.2989,  0.0778, -1.1424,  0.5875,
         0.0876,  0.0060, -0.3071,  0.3287,  0.2057,  0.3588,  0.5383,  0.0356,
        -0.4341, -0.6153, -0.1719, -0.2440,  0.2368,  0.6945, -1.3581,  0.5539],
       grad_fn=<SelectBackward0>)


In [146]:
array = np.array([[1, 2], [3, 4]])
print("Original array:", array)
qkv = nn.Linear(2, 4)(torch.tensor(array, dtype=torch.float32))
print("After Linear layer:", qkv)

Original array: [[1 2]
 [3 4]]
After Linear layer: tensor([[-0.4864, -1.3765, -0.3872, -2.0773],
        [-1.5242, -2.6500, -0.5154, -3.5167]], grad_fn=<AddmmBackward0>)


In [171]:
K

tensor([[[ 0.0876,  0.0060, -0.3071,  0.3287,  0.2057,  0.3588,  0.5383,
           0.0356],
         [-0.9506,  0.7599, -0.4849, -0.3653, -0.1188,  0.0494, -0.7666,
          -0.5839],
         [-0.7219,  2.2370,  0.4613,  0.1493, -0.0865, -0.3448, -0.0866,
           1.0914],
         [-0.4587,  0.2832, -0.7233, -0.3588, -0.0075, -0.8209, -0.9163,
          -0.8578]]], grad_fn=<SliceBackward0>)

In [172]:
K.transpose(-2, -1)

tensor([[[ 0.0876, -0.9506, -0.7219, -0.4587],
         [ 0.0060,  0.7599,  2.2370,  0.2832],
         [-0.3071, -0.4849,  0.4613, -0.7233],
         [ 0.3287, -0.3653,  0.1493, -0.3588],
         [ 0.2057, -0.1188, -0.0865, -0.0075],
         [ 0.3588,  0.0494, -0.3448, -0.8209],
         [ 0.5383, -0.7666, -0.0866, -0.9163],
         [ 0.0356, -0.5839,  1.0914, -0.8578]]], grad_fn=<TransposeBackward0>)